app/models/donation.rb
app/models/transfer.rb
app/models/user.rb
db/seeds.rb

complementar modelos com associações e criação do seed.

complement models validation and create seed

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/controllers/donations_controller.rb
app/controllers/receiver_profiles_controller.rb
app/views/donations/index.html.erb
test/controllers/receivers_controller_test.rb

Pessoal, terminei o view das doações (index) dos receivers. Por favor revisem.

Adding the receiver view

---

app/assets/stylesheets/components/_footer.scss
app/controllers/donations_controller.rb
app/views/donations/new.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/migrate/20200523191518_add_conservation_to_donations.rb
db/schema.rb

1. Criei a página new.
2. Ainda está com um erro na hora de criar (não aparece erro, mas o console não indica a criação do objeto e acredito que seja um problema no item :category_id. Verei na terça.
3. Ajustei o footer, que impactava na visualização.
4. Corrigi um erro de digitação na rota de transfers.

Created donation - new and create controllers actions and views

---

app/views/devise/registrations/new.html.erb
db/schema.rb

incluir mais opçoes para o signup

insert all option in signup form

---

app/controllers/donations_controller.rb
db/schema.rb

Oie, só adicionei uma condicional para aparecer as doacoes do usuario donor

Adding condition to user dono view

---

config/routes.rb
db/migrate/20200523135241_create_transfers.rb
db/schema.rb
db/seeds.rb

Consertei a migration para o schema sem receiver-id

Fixed schema problem

---

app/assets/stylesheets/components/_card.scss

Pessoal, só adicionei justify content nos card para melhorar a visualização

Adding some space between cards

---

app/controllers/donations_controller.rb
app/views/donations/edit.html.erb
config/routes.rb

create edit route, controller and view

---

app/views/devise/registrations/edit.html.erb
app/views/shared/_navbar.html.erb
db/schema.rb

editei o dropdown do nav bar e adicionei os links

edit drop down in nav bar and update edit view

---

app/controllers/donations_controller.rb
app/views/donations/edit.html.erb

adicionei a foto no formulario e acertei o controller.

add photo to edit form and controller

---

app/views/donations/index.html.erb

Adicionei a frase da doação

---

app/assets/stylesheets/components/_card.scss
app/views/donations/index.html.erb
app/views/pages/home.html.erb
config/environments/production.rb

Ajustei a homepage para ficar responsiva.

Responsive homepage

---

app/assets/stylesheets/components/_button.scss

Tirei o text-decoration do botao da home

Tirei o text-decoration do botao da home

---

app/views/donations/show.html.erb

adicionei mensagem para avisar que entrarão em contato dps com o doador.

add message to finish user journey

---

app/views/devise/registrations/edit.html.erb
app/views/devise/sessions/new.html.erb
app/views/donations/new.html.erb

Pessoal, coloqueio o botao  da home page em alguns outros lugares - Só o design

Ajustando o design dos botoes

---

app/views/donations/edit.html.erb
app/views/donations/show.html.erb

Pessoal, o caminho para editar a doação.

Inserção do link para editar a doação com os ícones

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

inseri uma linha para sair com os parametros donor e receiver e ajustei o application pois o devise nao estava aceitando os outros parametros do nosso modelo na hora de criar novos usuarios.

fix signup params

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/models/user.rb
app/views/donations/show.html.erb

Criada um página de doação com link para whatsapp do doador, na visão da instituição receiver.
Na visão do doador, a página exibe uma lista de instituições dentro do perfil.

Show donation fron end

---

app/controllers/donations_controller.rb
db/schema.rb

Ajustei algumas instance variables no donations controller

fixed heroku problem

---

app/assets/stylesheets/components/_bubbly.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/home.html.erb
db/schema.rb

no começo iria fazer resize mas na verdade fiz o balão saindo do rene

Resize banner image

---

app/models/user.rb

Precisei incluir dependent: :destroy para notifications, no user model. Isso gerava erro no heroku.

Fixed user model concerning its relationship with notificatios table

---

app/views/donations/show.html.erb

Fixed renezin image

---

app/views/donations/show.html.erb

Modifiquei para 100% o tamanho da imagem na show page.

Changed donation image width in the show page to 100%

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_donation.scss
app/views/donations/index.html.erb
app/views/donations/show.html.erb
app/views/shared/_navbar.html.erb

ajustes front

---

app/assets/stylesheets/components/_button.scss
app/controllers/donations_controller.rb
app/views/donations/show.html.erb

adicionei botoes para mudar o status no show donation

adding btn status

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_navbar.scss
app/views/donations/new.html.erb
app/views/shared/_navbar.html.erb
app/views/users/registrations/edit.html.erb
app/views/users/registrations/new.html.erb
app/views/users/sessions/new.html.erb

Pessoal, o icone da navbar nao estava aparecendo. Consertei aqui

Navbar icon

---

app/controllers/donations_controller.rb
app/views/donations/index.html.erb

adicionar distancias das doações e ordenar cards por distancias

Filter location

---

app/assets/stylesheets/components/_animation.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_testimony.scss
app/javascript/components/animation.js
app/views/pages/home.html.erb

Ajustando o circulo dos passos

---

db/seeds.rb

edit address and add images to seed

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_modal.scss
app/views/donations/show.html.erb
app/views/shared/_modal.html.erb

Pessoal, o modal com as infos das instituições

Donations show page

---

app/assets/stylesheets/components/_banner.scss

Fixed banner

---

app/assets/stylesheets/components/_form.scss

a form tava com width fix e não aparecia inteira no celular, alterei para 95% da tela.

fix form width

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/views/donations/index.html.erb

consegui acertar o controller para mostrar mais de uma categoria pro receiver. Mudei também o index do receiver para aparecer o link do whatsapp e coloquei o padrão do card mais parecido com o do doador, pos cor na distancia e coloquei a linha no meio do card.

making cards in same pattern and add whatsapp link

---

app/controllers/donations_controller.rb

acertei o controller para permitir mais de um tipo de doação por recebedor.

Fix donations controller

---

app/assets/config/manifest.js
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_modal.scss
app/assets/stylesheets/pages/_donation.scss
app/views/donations/index.html.erb
app/views/donations/new.html.erb
app/views/donations/show.html.erb

Oi gente, segue abaixo:
1- ajeitei a cor do footer
2- deixei a caixa do nome do usuario do donations/index fixo no topo
3 - deixei o modal aparecendo no meio da pagina e nao lá em cima
4 - fiz mini alterações no card do modal
5 -ajeitei o titulo da caixa azul onde ficam os receivers (mas precisa de melhores alterações ainda)
6 - deixei a foto do donation/show do tamanho correto porem ela corta a foto de qualquer jeito, entao ainda tem q acertar isso
beijos

changes modal, footer, cards, pic size

---

app/assets/stylesheets/components/_button.scss
app/views/donations/index.html.erb
app/views/donations/show.html.erb

o link do botao do whatsapp no index nao estava redirecionando para lnk algum, uma vez que que estava setado com a variavel @phone, que so existia no controller do show, e nao na do index. ajustei para resolver o problema. 
alem disso, centralizei o botao do donatios/show.

consertando erro com botao do zap no index

---

app/views/users/index.html.erb

Reduced maps height

---

app/assets/stylesheets/components/_avatar.scss

Colocando o heigth do sino fico em 40px para nao deformar

Colocando o heigth do sino
